"use client";
import {useCallback,useEffect,useState,useMemo} from 'react';
import {Activity,ArrowDown,ArrowLeft,ArrowRight,ArrowUp,Hand,ArrowUpRight,Bone,Box,Check,Expand,Focus,HeartPulse,Info,Layers3,LoaderCircle,Maximize,Minus,MousePointer2,Move,Plus,RotateCcw,ScanLine,Tag,X} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {INITIAL,type Structure,type ViewerState} from './anatomy-types';
import AnatomyScene from './anatomy-scene';
import OrganIndex from './organ-index';
import {DiagramControls,DiagramDetails} from './diagram-controls';
import {DIAGRAM_TISSUES,activeDiagramRoots,diagramRoot,diagramState,type DiagramRoot} from './anatomy-diagram';
import {selectionState,sexState,isStructureInSex,structureDrawState} from './anatomy-view';
const LAYERS=[{name:'골격계',en:'SKELETAL SYSTEM',icon:Bone},{name:'근육계',en:'MUSCULAR SYSTEM',icon:Activity},{name:'주요 장기·기관',en:'ORGANS & SENSES',icon:HeartPulse}];
const BASE_SOURCE='https://openstax.org/books/anatomy-and-physiology-2e/pages/';
export default function Home(){
 const [state,setState]=useState<ViewerState>(INITIAL),[structures,setStructures]=useState<Structure[]>([]),[progress,setProgress]=useState(0),[ready,setReady]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0),[info,setInfo]=useState(false),[diagramReady,setDiagramReady]=useState(false),[diagramError,setDiagramError]=useState(false);
 const available=useMemo(()=>structures.filter(p=>isStructureInSex(p,state.sex)),[structures,state.sex]);
 const patch=useCallback((v:Partial<ViewerState>)=>setState(s=>({...s,...v,...(v.selected===null&&s.mode==='diagram'?{mode:'whole' as const,diagramTissue:null}:{})})),[]);
 const choose=useCallback((id:string)=>{const part=available.find(p=>p.id===id);if(!part)return;setState(s=>selectionState(s,part));if(window.innerWidth<=800){document.querySelector('.viewer')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}},[available]);
 useEffect(()=>{const ac=new AbortController();fetch('/models/anatomy-v13.json',{signal:ac.signal}).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<Structure[]>;}).then(setStructures).catch(e=>{if(e.name!=='AbortError')setError('기관 정보 로딩 실패 · 재시도 필요');});return()=>ac.abort();},[retry]);
 const reset=useCallback(()=>{setState(s=>({...INITIAL,sex:s.sex,reset:s.reset+1,command:s.command+1}));},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setInfo(false);setState(s=>({...s,selected:null,isolate:false,mode:s.mode==='diagram'?'whole':s.mode,diagramTissue:null}));}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!context?.registerTool||!available.length)return;const lifecycle=new AbortController();const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'list_anatomy_structures',description:'List the anatomical structures available in this viewer.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({sex:state.sex,structures:available.map(p=>({id:p.id,name:p.name,system:p.system,parentId:p.parentId??null,childrenIds:p.childrenIds??[]}))})});register({name:'select_anatomy_structure',description:'Select an available structure and move the viewer camera to it.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||!('id' in input)||typeof input.id!=='string'||!available.some(p=>p.id===input.id))throw new Error('Unknown anatomy structure');choose(input.id);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return{selected:input.id};}});return()=>lifecycle.abort();},[available,choose,state.sex]);
 const selected=available.find(p=>p.id===state.selected);const visibleCount=available.filter(p=>structureDrawState(p,state).visible).length;
 const openDiagram=useCallback((root:DiagramRoot)=>setState(s=>({...diagramState(s,root),diagramHidden:[]})),[]);
 const selectTissue=useCallback((id:string)=>setState(s=>{const tissue=DIAGRAM_TISSUES.find(t=>t.id===id);if(!tissue||!activeDiagramRoots(s).includes(tissue.root))return s;return {...s,selected:tissue.root,diagramTissue:id,diagramHidden:s.diagramHidden.filter(v=>v!==id),focus:s.focus+1};}),[]);
 const mode=(v:string)=>setState(s=>v==='diagram'?{...diagramState(s,diagramRoot(s.selected)??'vagina'),diagramHidden:[]}:{...s,mode:v as ViewerState['mode'],diagramTissue:null,cut:50,focus:s.focus+1,command:s.selected?s.command:s.command+1});
 return <main className="atlas"><header className="app-header"><a className="brand" href="/" aria-label="Anatomy Atlas 홈"><span className="brand-mark"><Activity size={23}/></span><strong>ANATOMY<span>ATLAS</span></strong></a><span className="header-divider"/><span className="header-title">3D 인체 해부도</span><Tabs className="sex-tabs" value={state.sex} onValueChange={v=>setState(s=>sexState(s,v as ViewerState['sex']))}><span className="sex-caption">기관 구성</span><TabsList aria-label="성별별 기관 구성"><TabsTrigger value="male">남성</TabsTrigger><TabsTrigger value="female">여성</TabsTrigger></TabsList></Tabs><button className="icon-button info-toggle" onClick={()=>setInfo(!info)} aria-label="모델 및 출처 정보" aria-expanded={info}><Info size={19}/></button></header>
 {info&&<div className="source-popover"><button className="close-info icon-button" aria-label="정보 닫기" onClick={()=>setInfo(false)}><X size={17}/></button><strong>모델·출처</strong><p>공통 구조 · BodyParts3D 성인 남성 참조형</p><p>여성 골반·생식기관·방광·대장·유선 · HRA 여성 참조형<br/>폐 · HRA 참조형</p><p>세부 구조 · 원본 제공 범위<br/>단면 · 원본 표면 절개<br/>도해 · 질·자궁의 개략 조직층<br/>CT·MRI 미제공</p><a href="/ATTRIBUTION.md" target="_blank" rel="noreferrer">모델 출처·라이선스 <ArrowUpRight size={13}/></a><a href={BASE_SOURCE+'1-2-structural-organization-of-the-human-body'} target="_blank" rel="noreferrer">기능 · OpenStax Anatomy & Physiology 2e <ArrowUpRight size={13}/></a></div>}
 <div className="workspace"><aside className="left-panel" aria-label="해부학 표시 제어"><div className="panel-heading"><Layers3 size={18}/><h2>해부학 레이어</h2><span className="small-badge">03</span></div><div className="reference-scope"><p>골반·생식기관 · 성별 구분<br/>그 외 골격·근육 · 공통 참조형</p></div>
 {LAYERS.map((layer,i)=><section className={'layer-card '+(!state.visible[i]?'layer-off':'')} key={layer.name}><div className="layer-top"><span className={'layer-icon layer-'+i}><layer.icon size={21}/></span><div><h3>{layer.name}</h3><small>{layer.en}</small></div><Switch aria-label={layer.name+' 표시'} checked={state.visible[i]} onCheckedChange={v=>{setState(s=>({...s,visible:s.visible.map((a,n)=>n===i?v:a),selected:selected?.layer===i&&!v?null:s.selected,isolate:selected?.layer===i&&!v?false:s.isolate,mode:selected?.layer===i&&!v&&s.mode==='diagram'?'whole':s.mode,diagramTissue:selected?.layer===i&&!v?null:s.diagramTissue}));}}/></div><div className="range-caption"><span>투명도</span><b>{100-state.opacity[i]}%</b></div><Slider aria-label={layer.name+' 투명도'} value={[100-state.opacity[i]]} min={0} max={100} step={1} disabled={!state.visible[i]} onValueChange={v=>patch({opacity:state.opacity.map((a,n)=>n===i?100-v[0]:a)})}/></section>)}
 <div className="section-line"/><div className="setting-row"><span><Tag size={17}/>명칭 레이블</span><Switch checked={state.labels} onCheckedChange={v=>patch({labels:v})} aria-label="명칭 레이블 표시"/></div><div className="section-line"/><h3 className="minor-heading">보기 방식</h3>
 <Tabs value={state.mode} onValueChange={mode}><TabsList className="view-mode-tabs"><TabsTrigger value="whole"><Box size={18}/>전체</TabsTrigger><TabsTrigger value="explode"><Move size={18}/>분해</TabsTrigger><TabsTrigger value="section"><ScanLine size={18}/>단면</TabsTrigger><TabsTrigger value="diagram" disabled={state.sex!=='female'||!diagramReady} title="여성 구성 · 질·자궁"><Layers3 size={18}/>도해</TabsTrigger></TabsList></Tabs>
 {state.mode==='diagram'&&<DiagramControls state={state} patch={patch} onRoot={openDiagram}/>}
 {diagramError&&<p className="diagram-note">도해 로딩 실패 · 새로고침 필요</p>}
 {state.mode==='explode'&&<div className="mode-options"><div className="range-caption"><span>분해 간격</span><b>{state.explode}%</b></div><Slider aria-label="분해 간격" value={[state.explode]} onValueChange={v=>patch({explode:v[0]})}/></div>}
 {state.mode==='section'&&<div className="mode-options"><Tabs value={state.axis} onValueChange={v=>patch({axis:v as ViewerState['axis']})}><TabsList className="axis-tabs"><TabsTrigger value="z">관상</TabsTrigger><TabsTrigger value="x">시상</TabsTrigger><TabsTrigger value="y">횡단</TabsTrigger></TabsList></Tabs><div className="range-caption"><span>{selected?selected.name+' 절단 위치':'인체 절단 위치'}</span><b>{state.cut}%</b></div><Slider aria-label="단면 절단 위치" value={[state.cut]} min={0} max={100} onValueChange={v=>patch({cut:v[0]})}/><p>표면 절개 · 조직층 미제공</p></div>}
 <button className="reset-button" onClick={reset}><RotateCcw size={16}/>보기 초기화</button><p className="source-note">교육용 참조 · 임상용 아님</p></aside>
 <section className="viewer" aria-label="3D 해부학 뷰어"><div className="viewer-heading"><h1>{state.mode==='diagram'?'내부 구조 도해':state.mode==='section'?'단면 보기':state.mode==='explode'?'분해 보기':'3D 인체 해부도'}</h1><p>{state.navigation==='pan'?'드래그 이동 · 휠 확대':'드래그 회전 · 휠 확대'}</p>{state.mode==='diagram'&&<span className="diagram-view-badge">교육용 개략도 · 내강·층 두께 확대</span>}</div>
 <div className="view-direction"><span className="orientation-label">VIEW</span>{(['front','back','side'] as const).map((v,i)=><button key={v} className={state.view===v?'active':''} aria-label={['정면으로 이동','후면으로 이동','측면으로 이동'][i]} onClick={()=>patch({view:v,command:state.command+1,selected:null,isolate:false})}>{['정면','후면','측면'][i]}</button>)}</div>
 {structures.length>0&&!error&&<AnatomyScene key={retry} structures={structures} state={state} onSelect={choose} onDiagramSelect={selectTissue} onDiagramReady={()=>setDiagramReady(true)} onDiagramError={()=>setDiagramError(true)} onProgress={setProgress} onError={setError} onReady={()=>setReady(true)}/>}
 {!ready&&!error&&<div className="model-loading" role="status"><LoaderCircle size={28} className="spin"/><strong>모델 로딩 중</strong><div className="loading-track"><div style={{width:progress+'%'}}/></div><span>{progress}%</span></div>}
 {error&&<div className="viewer-error" role="alert"><Info size={25}/><p>{error}</p><button onClick={()=>{setError('');setReady(false);setDiagramReady(false);setDiagramError(false);setProgress(0);setRetry(v=>v+1);}}>다시 불러오기</button></div>}
 {ready&&<><Tabs className="navigation-tabs" value={state.navigation} onValueChange={v=>patch({navigation:v as ViewerState['navigation']})}><TabsList aria-label="모델 드래그 조작"><TabsTrigger value="rotate"><RotateCcw size={15}/>회전</TabsTrigger><TabsTrigger value="pan"><Hand size={15}/>이동</TabsTrigger></TabsList></Tabs><div className="pan-pad" role="group" aria-label="시점 이동"><button className="pan-up" aria-label="시점 위로 이동" title="시점 위로 이동 (↑)" onClick={()=>setState(s=>({...s,panY:s.panY-1}))}><ArrowUp size={16}/></button><button className="pan-left" aria-label="시점 왼쪽으로 이동" title="시점 왼쪽으로 이동 (←)" onClick={()=>setState(s=>({...s,panX:s.panX-1}))}><ArrowLeft size={16}/></button><Move className="pan-center" size={13} aria-hidden="true"/><button className="pan-right" aria-label="시점 오른쪽으로 이동" title="시점 오른쪽으로 이동 (→)" onClick={()=>setState(s=>({...s,panX:s.panX+1}))}><ArrowRight size={16}/></button><button className="pan-down" aria-label="시점 아래로 이동" title="시점 아래로 이동 (↓)" onClick={()=>setState(s=>({...s,panY:s.panY+1}))}><ArrowDown size={16}/></button></div><div className="camera-toolbar"><button title="확대" aria-label="확대" onClick={()=>patch({zoom:state.zoom+1})}><Plus size={19}/></button><button title="축소" aria-label="축소" onClick={()=>patch({zoom:state.zoom-1})}><Minus size={19}/></button><span/><button title="전체 인체 보기" aria-label="전체 인체 보기" onClick={()=>patch({selected:null,isolate:false,command:state.command+1})}><Maximize size={18}/></button><button title="정면으로 초기화" aria-label="카메라 정면 초기화" onClick={()=>patch({view:'front',selected:null,isolate:false,command:state.command+1})}><RotateCcw size={17}/></button></div></>}
 {selected&&<button className="selection-chip" onClick={()=>patch({selected:null,isolate:false})}><span/>{selected.name}<X size={14}/></button>}
 <div className="viewport-bottom"><span><Hand size={14}/>우클릭 드래그 · 이동</span><span>두 손가락 이동·확대</span><span>방향키 · 시점 이동</span></div>
 {!state.visible.some((v,i)=>v&&state.opacity[i]>0)&&ready&&<div className="all-hidden">표시 계통 없음<button onClick={reset}>보기 초기화</button></div>}
 </section>
 <aside className="right-panel" aria-label="기관 상세 정보"><div className="panel-heading"><Focus size={18}/><h2>기관 상세 정보</h2>{selected&&<button className="icon-button detail-close" aria-label="선택 해제" onClick={()=>patch({selected:null,isolate:false})}><X size={16}/></button>}</div>
 {selected?<div className="detail-content" key={selected.id}>{selected.parentId&&<button className="parent-structure-link" onClick={()=>choose(selected.parentId!)}>← {available.find(s=>s.id===selected.parentId)?.name} 전체</button>}<span className="info-kicker">{selected.en.toUpperCase()}</span><div className="detail-title"><span style={{background:selected.color}}/><h2 className="organ-title">{selected.name}</h2></div><span className="system-chip">{selected.system}</span>{selected.childrenIds&&<span className="detail-count">세부 {selected.childrenIds.length}</span>}{selected.description&&<p className="organ-summary">{selected.description}</p>}{selected.modelNote&&state.mode!=='diagram'&&<p className="structure-notice">{selected.modelNote}</p>}{state.mode==='diagram'&&<DiagramDetails state={state} patch={patch} onRoot={openDiagram} onTissue={selectTissue}/>}{selected.noticeBySex?.[state.sex]&&<p className="structure-notice">{selected.noticeBySex[state.sex]}</p>}{selected.relatedIds&&<div className="related-structures detail-related"><span className="related-caption">연결 구조</span>{available.filter(s=>selected.relatedIds?.includes(s.id)).map(s=><button className="organ-row substructure-row" key={s.id} onClick={()=>choose(s.id)}><span className="substructure-color" style={{background:s.color}}/>{s.name}</button>)}</div>}<div className="info-section"><h3>주요 기능</h3><ul className="function-list">{selected.functions.map(f=><li key={f}><span/>{f}</li>)}</ul></div>{selected.contextIds&&(state.mode==='whole'||state.mode==='diagram')&&<div className="setting-row context-setting"><span><Layers3 size={16}/>연결 구조</span><Switch checked={state.context&&!state.isolate} aria-label="생식기관 연결 구조 표시" onCheckedChange={v=>patch({context:v,isolate:false,diagramTissue:null,focus:state.focus+1})}/></div>}<div className="detail-actions"><button className="focus-action" onClick={()=>patch({context:false,focus:state.focus+1})}><Focus size={16}/>선택 확대</button><button className={'isolate-action '+(state.isolate?'is-active':'')} onClick={()=>patch({isolate:!state.isolate})}>{state.isolate?<Check size={16}/>:<Expand size={16}/>}단독 보기</button></div><a className="source-link" href={BASE_SOURCE+selected.source} target="_blank" rel="noreferrer">참고 자료 <ArrowUpRight size={13}/></a></div>:<div className="detail-content"><div className="selection-guide"><MousePointer2 size={19}/><span>모델·목록에서 기관 선택</span></div></div>}
 <OrganIndex structures={available} sex={state.sex} layers={LAYERS.map(layer=>layer.name)} selected={state.selected} ready={ready} onSelect={choose}/></aside></div>
 <footer className="statusbar"><span>ANATOMY ATLAS <b> / </b> BODY STRUCTURE EXPLORER</span><span>{ready?(state.sex==='male'?'남성':'여성')+' · '+visibleCount+'개 표시':'모델 준비 중'} <b>·</b> BodyParts3D <a href="/ATTRIBUTION.md" target="_blank" rel="noreferrer">CC BY 4.0</a></span></footer>
 </main>;
}
